# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_Analysis')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_Analysis')
    _Analysis = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_Analysis', [dirname(__file__)])
        except ImportError:
            import _Analysis
            return _Analysis
        try:
            _mod = imp.load_module('_Analysis', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _Analysis = swig_import_helper()
    del swig_import_helper
else:
    import _Analysis
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _Analysis.delete_SwigPyIterator
    __del__ = lambda self: None

    def value(self):
        return _Analysis.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _Analysis.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _Analysis.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _Analysis.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _Analysis.SwigPyIterator_equal(self, x)

    def copy(self):
        return _Analysis.SwigPyIterator_copy(self)

    def next(self):
        return _Analysis.SwigPyIterator_next(self)

    def __next__(self):
        return _Analysis.SwigPyIterator___next__(self)

    def previous(self):
        return _Analysis.SwigPyIterator_previous(self)

    def advance(self, n):
        return _Analysis.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _Analysis.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _Analysis.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _Analysis.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _Analysis.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _Analysis.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _Analysis.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self
SwigPyIterator_swigregister = _Analysis.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class VectorDouble(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, VectorDouble, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, VectorDouble, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _Analysis.VectorDouble_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _Analysis.VectorDouble___nonzero__(self)

    def __bool__(self):
        return _Analysis.VectorDouble___bool__(self)

    def __len__(self):
        return _Analysis.VectorDouble___len__(self)

    def __getslice__(self, i, j):
        return _Analysis.VectorDouble___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _Analysis.VectorDouble___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _Analysis.VectorDouble___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _Analysis.VectorDouble___delitem__(self, *args)

    def __getitem__(self, *args):
        return _Analysis.VectorDouble___getitem__(self, *args)

    def __setitem__(self, *args):
        return _Analysis.VectorDouble___setitem__(self, *args)

    def pop(self):
        return _Analysis.VectorDouble_pop(self)

    def append(self, x):
        return _Analysis.VectorDouble_append(self, x)

    def empty(self):
        return _Analysis.VectorDouble_empty(self)

    def size(self):
        return _Analysis.VectorDouble_size(self)

    def swap(self, v):
        return _Analysis.VectorDouble_swap(self, v)

    def begin(self):
        return _Analysis.VectorDouble_begin(self)

    def end(self):
        return _Analysis.VectorDouble_end(self)

    def rbegin(self):
        return _Analysis.VectorDouble_rbegin(self)

    def rend(self):
        return _Analysis.VectorDouble_rend(self)

    def clear(self):
        return _Analysis.VectorDouble_clear(self)

    def get_allocator(self):
        return _Analysis.VectorDouble_get_allocator(self)

    def pop_back(self):
        return _Analysis.VectorDouble_pop_back(self)

    def erase(self, *args):
        return _Analysis.VectorDouble_erase(self, *args)

    def __init__(self, *args):
        this = _Analysis.new_VectorDouble(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _Analysis.VectorDouble_push_back(self, x)

    def front(self):
        return _Analysis.VectorDouble_front(self)

    def back(self):
        return _Analysis.VectorDouble_back(self)

    def assign(self, n, x):
        return _Analysis.VectorDouble_assign(self, n, x)

    def resize(self, *args):
        return _Analysis.VectorDouble_resize(self, *args)

    def insert(self, *args):
        return _Analysis.VectorDouble_insert(self, *args)

    def reserve(self, n):
        return _Analysis.VectorDouble_reserve(self, n)

    def capacity(self):
        return _Analysis.VectorDouble_capacity(self)
    __swig_destroy__ = _Analysis.delete_VectorDouble
    __del__ = lambda self: None
VectorDouble_swigregister = _Analysis.VectorDouble_swigregister
VectorDouble_swigregister(VectorDouble)

class RandomNumber(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, RandomNumber, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, RandomNumber, name)
    __repr__ = _swig_repr

    def __init__(self):
        this = _Analysis.new_RandomNumber()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def get_uniform(self):
        return _Analysis.RandomNumber_get_uniform(self)

    def get_normal(self):
        return _Analysis.RandomNumber_get_normal(self)
    __swig_destroy__ = _Analysis.delete_RandomNumber
    __del__ = lambda self: None
RandomNumber_swigregister = _Analysis.RandomNumber_swigregister
RandomNumber_swigregister(RandomNumber)

class Analysis(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Analysis, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Analysis, name)
    __repr__ = _swig_repr
    LAB = _Analysis.Analysis_LAB
    TRUTH = _Analysis.Analysis_TRUTH
    VISIBLE = _Analysis.Analysis_VISIBLE
    CHARGED = _Analysis.Analysis_CHARGED

    def __init__(self, cmndfile, target, restframe, random_seed=-1, apply_smearing=False, debug=False):
        this = _Analysis.new_Analysis(cmndfile, target, restframe, random_seed, apply_smearing, debug)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _Analysis.delete_Analysis
    __del__ = lambda self: None

    def set_cuts(self, min_leading_pt, min_subleading_pt, max_eta, deltaR, min_MET, mass_lower, mass_upper):
        return _Analysis.Analysis_set_cuts(self, min_leading_pt, min_subleading_pt, max_eta, deltaR, min_MET, mass_lower, mass_upper)

    def get_n_accepted_events(self):
        return _Analysis.Analysis_get_n_accepted_events(self)

    def get_n_passed_mass_cuts(self):
        return _Analysis.Analysis_get_n_passed_mass_cuts(self)

    def get_n_tried_events(self):
        return _Analysis.Analysis_get_n_tried_events(self)

    def get_efficiency(self):
        return _Analysis.Analysis_get_efficiency(self)

    def get_cross_section(self):
        return _Analysis.Analysis_get_cross_section(self)

    def require_htautau(self, yes=True):
        return _Analysis.Analysis_require_htautau(self, yes)

    def process_event(self):
        return _Analysis.Analysis_process_event(self)

    def scan_past_brem(self, ip):
        return _Analysis.Analysis_scan_past_brem(self, ip)

    def unit(self, vec):
        return _Analysis.Analysis_unit(self, vec)

    def upsilon(self, charged, neutral):
        return _Analysis.Analysis_upsilon(self, charged, neutral)

    def acoplanarity(self, pim, pi0m, pip, pi0p, return_triple_corr=False):
        return _Analysis.Analysis_acoplanarity(self, pim, pi0m, pip, pi0p, return_triple_corr)

    def sum_met(self):
        return _Analysis.Analysis_sum_met(self)

    def total_transverse_mass(self, tau1, tau2, met):
        return _Analysis.Analysis_total_transverse_mass(self, tau1, tau2, met)

    def impact_param_vector(self, pion, privertex):
        return _Analysis.Analysis_impact_param_vector(self, pion, privertex)

    def b_tag(self, tauindex):
        return _Analysis.Analysis_b_tag(self, tauindex)

    def lepton_veto(self, minpt):
        return _Analysis.Analysis_lepton_veto(self, minpt)

    def smear_fourvector(self, pin, angular_res, energy_res):
        return _Analysis.Analysis_smear_fourvector(self, pin, angular_res, energy_res)
Analysis_swigregister = _Analysis.Analysis_swigregister
Analysis_swigregister(Analysis)

# This file is compatible with both classic and new-style classes.


